version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - prateekkumarweb
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - prateekkumarweb
