version: 2
updates:
  - package-ecosystem: npm
    directory: "/www"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - prateekkumarweb
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - prateekkumarweb
